# This is a basic workflow to help you get started with Actions
name: static_web_Deployment

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on: 
  push:
    branches:  master 
  # pull_request:
  #   branches: [ main ]

env:
  
  AWS_REGION : "us-east-1" 

# Permission can be added at job level or wocd ../rkflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  staticWebHosting:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}  #change to reflect your IAM role’s ARN
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: deploy static site
        run: aws s3 sync . s3://statwebhosting --delete
